import type { Metadata } from "next";
// import { Montserrat } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
import localFont from 'next/font/local';

const montserrat2 = localFont({
  src: './fonts/Montserrat-SemiBold.ttf',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={montserrat2.className}>
        {children}
      </body>
    </html>
  );
}


